### PR TITLE
added an example of how to use orb commands to install the cli as a step

### PR DESCRIPTION
**Pull request by jama22**
### Checklist
- [ ] All new jobs, commands, executors, parameters have descriptions
- [ ] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### Motivation, issues
I had a lot of trouble performing a basic deploy job with the orb, and it took a lot of study to figure out that I could just use the orb commands to do what I needed to do!
### Description
Added a new example `src/install_gcloud_cli_step.yml`. Hopefully it reads okay. I'm also assuming that adding a new `yml` entry will add to the examples on the orb registry. Feedback welcome!

### CODE REVIEW

**Comment by jama22** [comment]
@felicianotech or @iynere pinging you in case this got lost in your feed. Checked into the failing build but I have no idea how to fix, and it doesn't look related to the docs I submitted

**Comment by KyleTryon** [comment]
Hey @jama22 Sorry for the hiccup here. It appears the dev version of this orb needs to be refreshed to fix the config. The config currently imports a dev version of the orb (which this pipeline also creates) but it needs to be ran once every 90 days to keep the dev version active.

Because you have the permission to, would you mind publishing a dev version of this orb manually and then pushing a new commit to this Pr?

https://circleci.com/docs/2.0/orb-author-cli/#introduction-to-the-circleci-cli

You'll need to pack the src directory first.

`circleci orb pack src > orb.yml`

This will generate a single orb.yml file in the root directory. When that is complete you can publish a dev version of the orb.

`circleci orb publish orb.yml circleci/gcp-cli@dev:alpha`

This will fix the current error where the config file is not able to find a dev version and the pipeline should continue normally. Just push a new commit to this PR to trigger the tests again 👍

**Comment by jama22** [comment]
@KyleTryon Thanks for the update! I'll give it a shot this weekend

**Comment by lokst** [comment]
Closing this for now due to inactivity

**Pull request closed without merging**
